version: "3"
services:
    frontend:
      build: 
        dockerfile: frontend.Dockerfile
      ports:
        - 80:80
    backend:
      build: 
        dockerfile: backend.Dockerfile
      depends_on:
      - mongo
    mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: passwordRoot


