version: "3"
services:
    web:
      build: 
        context: frontend/
        dockerfile: frontend.Dockerfile
      ports:
        - 3000:80
    java:
      build: 
        context: backend/
        dockerfile: backend.Dockerfile
    mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example


